baseURL = 'https://albertec-itsolutions.github.io'
languageCode = 'en-us'
title = 'Albertec'
theme = 'spectral'

[params]
fancyTitle = "Albertec"
copyright = "Albertec IT Solutions"
description = 'Passionate provider of software and IT solutions'
body_is_markdown = true
#custom_css = "foo.css"
#images = ["path_to_social_image_for_link_previews.jpg"]

[[params.menu.main]]
url = '/'
title = "Home"

[[params.menu.main]]
url = '/#three'
title = "Services"

[[params.menu.main]]
url = '/#contact'
title = "Contact Us"

[params.three]
enable = true
title = 'Services'
body = '''
We provide the following expert services
'''

[[params.three.feature]]
icon = "fa-code"
title = "Custom Sofware"
body = "We specialise in mobile and web application development."

[[params.three.feature]]
icon = "fa-laptop"
title = "PC and IT Hardware"
body = "Including but to limited to laptops, desktop computers, servers, networking infrastructure."

[params.contact]
enable = true
title = "Contact"
body = "Leave us a message."
email = "albertec.itsolutions@gmail.com"
subject = "New submission from albertec website"
plain = false

[params.social]
twitter = ""
facebook = ""
instagram = ""
dribble = ""
